<div class="page-heading"><div><p class="eyebrow text-muted">STAFF CRM</p><h1><?=e(t('welcome'))?></h1></div>
</div>
<nav class="tab-nav nav nav-tabs customtab" aria-label="Dashboard"><a data-tab="network" class="nav-link <?=$tab==='network'?'active':''?>" href="<?=e(routeUrl('dashboard',array_merge(['tab'=>'network'],$report->params)))?>"><?=e(t('network'))?></a><a data-tab="statistics" class="nav-link <?=$tab==='statistics'?'active':''?>" href="<?=e(routeUrl('dashboard',['tab'=>'statistics']))?>"><?=e(t('statistics'))?></a><a data-tab="orders" class="nav-link <?=$tab==='orders'?'active':''?>" href="<?=e(routeUrl('dashboard',['tab'=>'orders']))?>"><?=e(t('orders'))?></a></nav>
<section id="network-panel" class="tab-panel" <?=$tab==='network'?'':'hidden'?>>
<form method="get" class="period-form report-form"><input type="hidden" name="route" value="dashboard"><input type="hidden" name="tab" value="network">
<label for="report-mode"><?=e(t('report'))?></label><select id="report-mode" name="report" class="form-control"><?php foreach(['all','year','month','range'] as $mode): ?><option value="<?=$mode?>" <?=$report->mode===$mode?'selected':''?>><?=e(t('report_'.$mode))?></option><?php endforeach; ?></select>
<div class="report-fields" data-report-mode="year" <?=$report->mode==='year'?'':'hidden'?>><label for="report-year"><?=e(t('year'))?></label><input id="report-year" name="year" class="form-control" type="number" min="1000" max="9999" value="<?=e($report->year)?>" <?=$report->mode==='year'?'':'disabled'?>></div>
<div class="report-fields" data-report-mode="month" <?=$report->mode==='month'?'':'hidden'?>><label for="period"><?=e(t('month'))?></label><select id="period" name="period" class="form-control" <?=$report->mode==='month'?'':'disabled'?>><option value="current" <?=($report->params['period']??'')==='current'?'selected':''?>><?=e(t('current_month'))?></option><?php $monthChoices=array_unique(array_merge([$report->period],$periods));rsort($monthChoices);foreach($monthChoices as $p): ?><option value="<?=e($p)?>" <?=($report->params['period']??'')===$p?'selected':''?>><?=e($p)?></option><?php endforeach; ?></select><input id="report-month" type="month" class="form-control" aria-label="<?=e(t('select_month'))?>" value="<?=e($report->period)?>"></div>
<div class="report-fields" data-report-mode="range" <?=$report->mode==='range'?'':'hidden'?>><label for="date-start"><?=e(t('date_from'))?></label><input id="date-start" name="date_start" type="date" class="form-control" value="<?=e($report->dateStart)?>" <?=$report->mode==='range'?'':'disabled'?>><label for="date-end"><?=e(t('date_to'))?></label><input id="date-end" name="date_end" type="date" class="form-control" value="<?=e($report->dateEnd)?>" <?=$report->mode==='range'?'':'disabled'?>></div>
<button class="btn btn-primary"><?=e(t('apply'))?></button></form>
<p class="report-explanation small text-muted"><?=e(t('snapshot_report_note'))?></p>
 <div class="coverage text-muted"><span><?=e(t('report'))?>: <strong><?=e($period??'—')?></strong></span><span><?=e(t('coverage'))?>: <strong><?=count(array_filter($rows,function($row){return $row['collected_at']!==null;}))?> / <?=count($rows)?></strong></span></div>
 <div class="metric-grid"><article class="metric-card card"><span class="metric-label text-muted"><?=e(t('crm_total'))?></span><strong><?=count($rows)?></strong><span class="metric-note text-muted">STAFF CRM</span></article>
 <?php foreach($totals as $metric=>$sum): ?><article class="metric-card card"><span class="metric-label text-muted"><?=e(t($metric))?></span><strong><?=numberValue($sum['value'])?></strong><span class="metric-note text-muted"><?=$sum['value']===null?e(t('no_data')):(!$sum['complete']?e(t('partial')).' · '.$sum['known'].' / '.count($rows):e($period??''))?></span></article><?php endforeach; ?></div>
 <section class="panel card card-body"><div class="panel-heading"><h2><?=e(t('map'))?></h2><span class="text-muted"><?=e(t('no_location'))?>: <?=count(array_filter($rows,function($row){return Statistics::coordinates($row)===null;}))?></span></div>
 <div id="network-map" class="map" data-map-url="<?=e(routeUrl('map',$report->params))?>" aria-label="<?=e(t('map'))?>"></div><div class="map-error text-warning" role="status" hidden></div>
 <?php if(!$rows): ?><p class="empty-state text-muted"><?=e(t('empty'))?></p><?php endif; ?>
 <?php $unknown=array_filter($rows,function($row){return Statistics::coordinates($row)===null;}); if($unknown): ?><div class="unknown-list"><strong><?=e(t('no_location'))?></strong><?php foreach($unknown as $row): ?><a href="<?=e(routeUrl('installation',['uuid'=>$row['uuid']]))?>"><?=e($row['name'])?></a><?php endforeach; ?></div><?php endif; ?>
 </section>
</section>
<section id="statistics-panel" class="tab-panel" <?=$tab==='statistics'?'':'hidden'?>>
<section class="panel card card-body"><div class="panel-heading"><h2><?=e(t('statistics'))?></h2><span class="text-muted"><?=e(t('latest_data'))?></span></div>
<div class="table-wrap"><table id="crm-table" class="table table-hover"><thead><tr><?php foreach(['church','country','postcode','registered','last_collection','status','members_total'] as $label): ?><th><?=e(t($label))?></th><?php endforeach; ?></tr></thead><tbody>
<?php foreach($registryRows as $row): ?><tr><td><a class="church-link text-info" href="<?=e(routeUrl('installation',['uuid'=>$row['uuid']]))?>"><?=e($row['name'])?></a></td><td><?=e($row['country_iso']??'—')?></td><td><?=e($row['postcode']??'—')?></td><td><?=e($row['registered_at'])?></td><td><?=e($row['last_collected_at']??'—')?></td><td><?php $state=$row['latest_success']!==null && (int)$row['latest_success']===0?'failed':($row['collected_at']!==null?'received':'missing'); ?><span class="state badge badge-pill <?=$state==='received'?'badge-success':($state==='failed'?'badge-danger':'badge-light')?>"><?=e(t($state))?></span></td><td data-order="<?=e($row['members_total']??-1)?>"><?=numberValue($row['members_total'])?></td></tr><?php endforeach; ?>
</tbody></table></div><p class="small text-muted"><?=e(t('utc'))?></p>
</section></section>

<section id="orders-panel" class="tab-panel" <?=$tab==='orders'?'':'hidden'?>><?php require __DIR__.'/orders.php'; ?></section>
