<a class="back-link" href="<?=e(routeUrl('dashboard',['tab'=>'statistics']))?>">← <?=e(t('back'))?></a>
<div class="page-heading"><div><p class="eyebrow">STAFF CRM</p><h1><?=e($installation['name'])?></h1></div><span class="state received"><?=e(t('snapshot_count'))?>: <?=count($installation['snapshots'])?></span></div>
<div class="detail-grid"><section class="panel"><h2><?=e(t('installation'))?></h2><dl class="installation-meta">
<?php foreach(['uuid'=>'UUID','api_url'=>t('api_url'),'country_iso'=>t('country'),'postcode'=>t('postcode'),'registered_at'=>t('registered')] as $field=>$label): ?><dt><?=e($label)?></dt><dd><?=e($installation[$field]??'—')?></dd><?php endforeach; ?>
<dt><?=e(t('status'))?></dt><dd><?=e($installation['attempts'] ? t((int)$installation['attempts'][0]['success']===1?'success':'failed') : t($installation['snapshots']?'received':'missing'))?></dd>
</dl></section><section class="panel"><h2><?=e(t('map'))?></h2><?php $coordinates=Statistics::coordinates($installation); if($coordinates): ?><div id="installation-map" class="map detail-map" data-point="<?=e(json_encode(['name'=>$installation['name'],'lat'=>$coordinates[0],'lng'=>$coordinates[1],'source'=>$coordinates[2]],JSON_THROW_ON_ERROR))?>"></div><div class="map-error" hidden role="status"></div><?php else: ?><p class="empty-state"><?=e(t('no_location'))?></p><?php endif; ?></section></div>
<section class="panel"><div class="panel-heading"><h2><?=e(t('history'))?></h2><span class="muted"><?=e(t('utc'))?></span></div>
<?php if(!$installation['snapshots']): ?><p class="empty-state"><?=e(t('all_periods'))?></p><?php endif; ?>
<?php foreach($installation['snapshots'] as $snapshot): ?><article class="snapshot"><h3><?=e($snapshot['reporting_period'])?></h3><div class="snapshot-times"><span><?=e(t('generated'))?>: <?=e($snapshot['generated_at'])?></span><span><?=e(t('collected'))?>: <?=e($snapshot['collected_at'])?></span></div><dl class="snapshot-metrics"><?php foreach(Statistics::METRICS as $metric): ?><div><dt><?=e(t($metric))?></dt><dd><?=numberValue($snapshot[$metric])?></dd></div><?php endforeach; ?><div><dt><?=e(t('last_successful_login'))?></dt><dd><?=e($snapshot['last_successful_login']??'—')?></dd></div></dl></article><?php endforeach; ?>
</section>
<?php if($installation['attempts']): ?><section class="panel"><h2><?=e(t('attempts'))?></h2><div class="table-wrap"><table class="table"><thead><tr><th><?=e(t('period'))?></th><th><?=e(t('collected'))?></th><th><?=e(t('status'))?></th><th><?=e(t('error_code'))?></th></tr></thead><tbody><?php foreach($installation['attempts'] as $attempt): ?><tr><td><?=e($attempt['reporting_period'])?></td><td><?=e($attempt['attempted_at'])?></td><td><?=e(t((int)$attempt['success']===1?'success':'failed'))?></td><td><?=e($attempt['error_code']??'—')?></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
