<section class="panel card card-body">
<div class="panel-heading"><h2><?=e(t('orders'))?></h2><button class="btn btn-primary" type="button" data-toggle="collapse" data-target="#order-add-form" aria-expanded="false" aria-controls="order-add-form"><?=e(t('order_add'))?></button></div>
<?php if($orderSaved): ?><div class="alert alert-success" role="status"><?=e(t('order_saved'))?></div><?php endif; ?>
<div class="collapse mb-4" id="order-add-form"><form method="post" action="<?=e(routeUrl('order-add'))?>"><input type="hidden" name="csrf" value="<?=e($auth->csrf())?>"><div class="order-fields">
<?php foreach(['contact','email','phone','city','church','members','ip','order_date'] as $field): ?><div class="form-group"><label for="order-new-<?=$field?>"><?=e(t('order_'.$field))?></label><input id="order-new-<?=$field?>" name="<?=$field?>" class="form-control" type="<?=$field==='email'?'email':($field==='order_date'?'date':'text')?>" <?=$field==='contact'||$field==='email'||$field==='order_date'?'required':''?> value="<?=$field==='order_date'?date('Y-m-d'):''?>"></div><?php endforeach; ?>
</div><div class="form-group"><label for="order-new-message"><?=e(t('order_message'))?></label><textarea id="order-new-message" name="message" class="form-control" maxlength="10000" rows="3"></textarea></div><button class="btn btn-primary" type="submit"><?=e(t('save'))?></button></form></div>
<div class="table-wrap"><table id="orders-table" class="table table-hover orders-table"><thead><tr><?php foreach(['order_date','contact','email','phone','city','church','members','message','ip','status','comment','actions'] as $field): ?><th><?=e(t('order_'.$field))?></th><?php endforeach; ?></tr></thead><tbody>
<?php foreach($orders as $order): $form='order-save-'.$order['id']; ?><tr>
<td data-order="<?=e($order['order_date'])?>"><?=e(date('d.m.Y',strtotime($order['order_date'])))?></td>
<?php foreach(['contact','email','phone','city','church','members','message','ip'] as $field): ?><td class="<?=$field==='message'?'order-message':''?>"><?=nl2br(e($order[$field]))?></td><?php endforeach; ?>
<td data-order="<?=e($order['status'])?>"><select class="form-control" name="status" form="<?=$form?>" aria-label="<?=e(t('order_status').' · '.$order['contact'])?>"><?php foreach(Orders::STATUSES as $status): ?><option value="<?=$status?>" <?=$order['status']===$status?'selected':''?>><?=e(t('order_status_'.$status))?></option><?php endforeach; ?></select></td>
<td><textarea class="form-control order-comment" name="comment" form="<?=$form?>" maxlength="10000" rows="3" aria-label="<?=e(t('order_comment').' · '.$order['contact'])?>"><?=e($order['comment'])?></textarea></td>
<td><form id="<?=$form?>" method="post" action="<?=e(routeUrl('order-save'))?>"><input type="hidden" name="csrf" value="<?=e($auth->csrf())?>"><input type="hidden" name="id" value="<?=e($order['id'])?>"><input type="hidden" name="version" value="<?=e($order['version'])?>"><button class="btn btn-primary btn-sm" type="submit"><?=e(t('save'))?></button></form></td>
</tr><?php endforeach; ?></tbody></table></div></section>
